### ISSUE TITLE
DeepCut Tokenize Error

### ISSUE THREAD

**Issue by CherryChann** [rkcosmos/deepcut#38] opened 2018-08-23 09:13 UTC
I have a problem concerned with using deepcut.tokenize. It is fine if i use outside of my project but i need to use deepcut.tokenize before starting my application. if not i got that error, "ValueError: Tensor Tensor("dense_14/Sigmoid:0", shape=(?, 1), dtype=float32) is not an element of this graph". I m using deepCut: version 0.6.0.0, tensorflow: version 1.10.0.

**Comment by titipata** [comment] 2018-10-01 21:30
@CherryChann, did you solve this problem? I cannot reproduce the error that you got. It would be great if I can have more details.

**Comment by CherryChann** [comment] 2018-10-04 05:21
@titipata I have called deepcut.tokenize before starting app. 
Before calling deepcut.tokenize, I need to call this method with another word. For example: 
"import deepcut
print(deepcut.tokenize('ตัดคำได้ดีมาก'))
deepcut.tokenize('ตัดคำไ')"

But i think this is not
a correct solution. Also right now I m having a problem for deepcut.tokenize.
I got this error :

" ValueError: Tensor Tensor("dense_14/Sigmoid:0", shape=(?, 1),
dtype=float32) is not an element of this graph."
This error comes from y_predict = model.predict([x_char, x_type]) from
deepcut library. My tensorflow version is 1.10.0 and deepcut version is
(0.6.0.0).

**Comment by titipata** [comment] 2019-11-06 18:03
@CherryChann I'll close this issue for now as we move to version `0.7.0`. Let me know if the current version of the deepcut `0.7.0` works for you.

**Closed as completed by titipata** 2019-11-06 18:03 UTC
